const data = [
    {
        title: 'Tuscan Leather',
        album: 'Nothing Was The Same',
        artistes: ['Drake'],
        cover: '/images/ntws.jpg',
        liked: false,
        explicit: true,
    },
    {
        title: 'Bad Idea',
        album: 'The Lost Boy',
        artistes: ['YBN Cordae', 'Chance The Rapper'],
        cover: '/images/badidea.jpg',
        liked: true,
        explicit: true,
    },
    {
        title: 'LOVE AGAIN',
        album: 'CASE STUDY 01',
        artistes: ['Daniel Caesar', 'Brandy'],
        cover: '/images/casestudy.jpg',
        liked: true,
        explicit: false,
    },
    {
        title: 'Say Na',
        album: 'RESET',
        artistes: ['Moneybagg', 'J. Cole'],
        cover: '/images/sayna.jpg',
        liked: false,
        explicit: true,
    },
    {
        title: 'P*$$Y Fairy (OTW)',
        album: '',
        artistes: ['Jhene Aiko'],
        cover: '/images/chillombo.jpg',
        liked: false,
        explicit: true,
    },
    {
        title: 'I Spy',
        album: '',
        artistes: ['Lila Ike'],
        cover: '/images/ispy.png',
        liked: true,
        explicit: false,
    },
    {
        title: 'Besame mucho',
        album: "40 titres d'or",
        artistes: ['Tino Rossi'],
        cover: '/images/besamemucho.jpg',
        liked: false,
        explicit: true,
    },
    {
        title: 'Not Coming Back',
        album: '1123',
        artistes: ['BJ The Chicago Kid', 'PJ Morton'],
        cover: '/images/notcomingback.jpg',
        liked: false,
        explicit: false,
    },
]

export default data
